apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T12:30:12Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "2080"
  uid: 0853ab43-18e5-4cc4-bbe3-eb3780e5a66c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.147.154
  clusterIPs:
  - 10.109.147.154
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32689
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
